# Generated by Django 4.0 on 2021-12-13 11:14

import artapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField(blank=True, max_length=1000, null=True)),
                ('score', models.DecimalField(decimal_places=5, default=5, max_digits=7)),
                ('like', models.IntegerField(default=0)),
                ('place_name', models.CharField(max_length=50)),
                ('pic_upload', models.FileField(upload_to=artapp.models.user_directory_path)),
            ],
            bases=(models.Model, artapp.models.convertJSON),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, max_length=1000, null=True)),
                ('author', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, max_length=1000, null=True)),
                ('score', models.DecimalField(decimal_places=5, default=5, max_digits=7)),
                ('like', models.IntegerField(default=0)),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artapp.museum')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('tel', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('none', '保密'), ('male', '男'), ('female', '女')], default='保密', max_length=10)),
                ('description', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['c_time'],
            },
            bases=(models.Model, artapp.models.convertJSON),
        ),
        migrations.CreateModel(
            name='Show_Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('like', models.IntegerField(default=0)),
                ('m_time', models.DateTimeField(auto_now=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artapp.show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artapp.user')),
            ],
            options={
                'ordering': ['-m_time'],
            },
        ),
        migrations.CreateModel(
            name='News_Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('like', models.IntegerField(default=0)),
                ('m_time', models.DateTimeField(auto_now=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artapp.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artapp.user')),
            ],
            options={
                'ordering': ['-m_time'],
            },
        ),
        migrations.CreateModel(
            name='Museum_Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('like', models.IntegerField(default=0)),
                ('m_time', models.DateTimeField(auto_now=True)),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artapp.museum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artapp.user')),
            ],
            options={
                'ordering': ['-m_time'],
            },
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, max_length=1000, null=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artapp.show')),
            ],
        ),
    ]
