# Generated by Django 4.0 on 2021-12-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0002_data_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_record',
            name='update_type',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
