# Generated by Django 4.0 on 2021-12-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0003_alter_data_record_update_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_record',
            name='idNum',
            field=models.DecimalField(decimal_places=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='data_record',
            name='update_type',
            field=models.DecimalField(decimal_places=0, editable=False, max_digits=2),
        ),
    ]
