# Generated by Django 4.0 on 2021-12-26 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0005_alter_data_record_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data_record',
            options={'ordering': ['update_time'], 'verbose_name': '用户备份与恢复日志', 'verbose_name_plural': '用户备份与恢复日志'},
        ),
    ]
